Accounts/urls.py
from django.urls import path
from Accounts import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('<str:usernam>/update/', views.update_user_details, name='update-user'),
    path('<str:username>/delete/', views.delete_user, name='delete-user'),
    path('logout/', views.logout_user, name='logout')
]

MakeAPolls/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('Polls.urls')),
    path('account/', include('Accounts.urls'))
]
if settings.DEBUG == True:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Polls/urls.py
from django.urls import path
from Polls import views

app_name = 'polls'

urlpatterns = [
    path('', views.all_polls, name='all-polls'),
    path('create-poll/', views.create_poll, name='create-poll'),
    path('<str:username>/<slug:slug>', views.view_poll, name='view-poll'),
    path('<str:username>/<slug:slug>', views.delete_poll, name='delete-poll'),
    path('<str:username>/<slug:slug>/vote', views.vote, name='vote'),
    path('<str:username>/<slug:slug>/result', views.result, name='result'),
    path('<str:username>/<slug:slug>/edit', views.edit_poll, name="edit-poll")
]

Polls/models.py
from django.db import models, IntegrityError
from django.conf import settings
from django.forms import ValidationError
from django.utils import timezone
from django.template.defaultfilters import slugify
import datetime

STATUS = [
    ('draft', 'DRAFT'),
    ('published', 'PUBLISHED')
]


class SoftDeleteManager(models.Manager):
    def with_deleted(self):
        return super().get_queryset().all()


class SoftDeleteModel(models.Model):
    deleted_at = models.DateTimeField(blank=True, null=True)

    objects = SoftDeleteManager()

    class Meta:
        abstract = True

    def soft_delete(self):
        self.deleted_at = timezone.now()
        self.save()

    def restore(self):
        self.deleted_at = None
        self.save()


class Question(SoftDeleteModel, models.Model):
    author      = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title       = models.CharField(max_length=50)
    slug        = models.SlugField(max_length=50) # editable=False also fix admin issue with slugs
    description = models.CharField(max_length=50, null=True, blank=True)
    thumbnail   = models.ImageField(upload_to='uploads/%Y/%m/%d/', null=True, blank=True)
    question    = models.CharField(max_length=255)
    pub_date    = models.DateTimeField(verbose_name='Date published', default=timezone.now) # remove default and set auto_now_add=True
    updated_at  = models.DateTimeField(verbose_name='Last update', default=timezone.now) # remove default and set auto_now=True
    status      = models.CharField(max_length=9, default='published', choices=STATUS)

    def __str__(self):
        return self.title
    
    # switching to ModelForm might make this obsolete
    # Override save method to automatically create slugs # USE THIS IN PRODUCTION
    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = slugify(self.title)
    #     return super().save(*args, **kwargs)

    # Temporary solution
    def save(self, *args, **kwargs):
        if self.status == 'draft':
            self.slug = slugify(self.title)
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def save_as_draft(self):
        self.pub_date = None
        self.updated_at = None
        self.status = 'draft'
        self.save()
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
    class Meta:
        db_table = 'Questions'
        constraints = [
            models.UniqueConstraint(fields=['author', 'title'], name='unique_author_question_title', violation_error_message='Title already exists')
        ]
        permissions = [
            ('can_hide_poll', 'can hide poll')
        ]

    

# Create choice model
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    text     = models.CharField(max_length=255)
    votes    = models.IntegerField(default=0)

    def __str__(self):
        return self.text

    class Meta:
        db_table = 'Choices'

Polls/forms.py
from django import forms
from django.forms import ValidationError, formset_factory, inlineformset_factory
from django.forms import BaseFormSet, BaseInlineFormSet
from Polls.models import Question, Choice


STATUS = {
    'published':'PUBLISHED',
    'draft':'DRAFT'
}


class ChoiceForm(forms.Form):
    text = forms.CharField(max_length=255, label='Choice')


# This class inherits from BaseFormSet. This is use to override the validation behaviour of a formset.
# The formset.is_valid is always True because it passes an empty string or a None value as default value. 
#So if any of the form should return the default value. raise a validation error.
class BaseChoiceFormSet(BaseFormSet):
    def clean(self):
        if any(self.errors):
            return
        
        for form in self.forms:
            choice_text = form.cleaned_data.get('text')
            if choice_text == None or choice_text == "":
                form.add_error('text',  "Please provide a text for this choice.")
                # raise ValidationError("Please provide a text for all choice fields.")
            

# This formset is used to generate and handle multiple Choice Form
class ChoiceFormFormSet:
    ChoiceFormset = formset_factory(ChoiceForm, BaseChoiceFormSet, extra=3, max_num=3)

# switch to model form so as to pass the model instance to the form
class QuestionForm(forms.ModelForm):
    title = forms.CharField(max_length=50, required=True)
    description = forms.CharField(widget=forms.Textarea, required=True)
    thumbnail = forms.ImageField(required=False)
    question = forms.CharField(max_length=255, required=True)
    status = forms.ChoiceField(choices=STATUS, widget=forms.Select, required=True)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)  # Retrieve user object from kwargs
        super(QuestionForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Question
        fields = ['title', 'description', 'thumbnail', 'question', 'status']
    

class EditChoiceFormSet(forms.Form):
    EditChoiceFormset = formset_factory(ChoiceForm, BaseChoiceFormSet, extra=0, max_num=3) # check if poll has choice if not extra should not be 0

# class EditChoiceInlineFormset():
#     EditChoiceFormset = inlineformset_factory(Question, Choice, fields=['text'], max_num=3)

Polls/views.py
'''TODO: CHANGE ALL questions to polls'''

from django.forms import ValidationError, formset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_list_or_404, redirect, render
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from Polls.models import Choice, Question, IntegrityError
from Polls.forms import ChoiceForm, QuestionForm, ChoiceFormFormSet, EditChoiceFormSet
from django.contrib.sessions.models import Session
from pprint import pprint

@login_required(login_url='accounts:login')
def create_poll(request):
    context = {}
    user=request.user

    if request.method == 'POST':
        formset = ChoiceFormFormSet.ChoiceFormset(request.POST)
        poll_form = QuestionForm( request.POST, request.FILES, instance=None, user=user)
        if poll_form.is_valid() and formset.is_valid():
            question = Question(
                user = user,
                title = poll_form.cleaned_data.get('title'),
                description = poll_form.cleaned_data.get('description'),
                thumbnail = poll_form.cleaned_data.get('thumbnail'),
                question = poll_form.cleaned_data.get('question'),
                status = poll_form.cleaned_data.get('status'),
            )
            try:
                question.save() # raises an IntegrityError if the title already exists for a particlar user
            except IntegrityError as e:
                poll_form.add_error('title', 'Title already exists')
            else:
                for i in range(len(formset)):
                    Choice.objects.create(
                        question=question,
                        text = formset.cleaned_data[i].get('text')
                    )
                return HttpResponseRedirect(reverse('polls:all-polls'))#work on this
        else:
            context['error'] = "Form contains errors"
    else:
        poll_form = QuestionForm()
        formset = ChoiceFormFormSet.ChoiceFormset()
    
    context['poll_form'] = poll_form
    context['formset'] = formset

    return render(request, 'Polls/create_poll.html', context)

def view_poll(request, username, slug):
    
    poll = get_object_or_404(Question, author__username=username, slug=slug)
    context = {'poll':poll}
    return render(request, 'Polls/detail_poll.html', context)

def all_polls(request):
    # polls = Question.objects.all().filter(status='published')[::1]
    user = request.user
    print(user)
    print(user.has_perm('Polls.delete_question'))
    pprint(user.get_user_permissions())
    pprint(user.get_group_permissions())
    # pprint(user.get_all_permissions())

    polls = Question.objects.all()[::1]
    voted_polls_in_session = request.session.get('user_voted_polls', False)

    if not voted_polls_in_session:
        request.session['user_voted_polls'] = []
        voted_polls = request.session['user_voted_polls']
    else:
        voted_polls_objects = get_list_or_404(Question, pk__in=voted_polls_in_session)
        voted_polls = sorted(voted_polls_objects, key=lambda x: voted_polls_in_session.index(x.id))
    
    context = {'polls':polls, 'voted_polls':voted_polls}
    # s = Session.objects.get(pk='egm9pfy5ikt29y64q2recxyj74m92wwt')
    # print(s.get_decoded())

    return render(request, 'Polls/home.html', context)

def delete_poll():
    ...

@login_required(login_url='accounts:login')
def vote(request, username, slug):
    poll = get_object_or_404(Question, author__username=username, slug=slug)
    try:
        choice_id = request.POST.get('choice')
        selected_choice = poll.choices.get(pk=choice_id)
    except (KeyError,  Choice.DoesNotExist):
        context = {'poll':poll, 'error_message':'You did not select a choice'}
        return render(request, 'Polls/detail_poll.html', context)
    else:
        selected_choice.votes+=1
        selected_choice.save()

        if 'user_voted_polls' in request.session:
            voted_polls = request.session.get('user_voted_polls')

            if poll.id in voted_polls:
                voted_polls.remove(poll.id)

            request.session['user_voted_polls'].insert(0, poll.id)

            if len(voted_polls) > 3:
                voted_polls.pop()

        return HttpResponseRedirect(reverse('polls:result', args=[username, slug]))

@login_required(login_url='accounts:login')
def result(request, username, slug):
    poll = get_object_or_404(Question, author__username=username, slug=slug)
    choices = get_list_or_404(Choice, question=poll)

    context = {'choices':choices, 'poll':poll}
    return render(request, 'Polls/result.html', context)


'''TODO: make choice formset dynamic if status is draft i.e allow for creating and deleting choice formset forms
         allow for saving empty choice formset forms
'''
def edit_poll(request, username, slug):
    # get the object
    context = {}
    poll = get_object_or_404(Question, user__username=username, slug=slug)
    choices = get_list_or_404(Choice, question=poll)
    user = request.user
    

    # check if the post or get method
    if request.method == 'POST':

        # populate the poll form and choice formset
        poll_form = QuestionForm(request.POST, instance=poll)
        formset = EditChoiceFormSet.EditChoiceFormset(request.POST)

        # check if the forms are valid
        if poll_form.is_valid() and formset.is_valid():

            poll.user = user
            poll.title = poll_form.cleaned_data.get('title')
            poll.description = poll_form.cleaned_data.get('description')
            poll.thumbnail = poll_form.cleaned_data.get('thumbnail')
            poll.question = poll_form.cleaned_data.get('question')
            poll.status = poll_form.cleaned_data.get('status')
            poll.save()

            # Fix this. ChoiceFormset should return just 3 forms and should be updated

            # check if choice exists on question i.e question.choices
            # print(len(formset.forms))
            for i in range(len(choices)):
            # iterate over form and choice list and assign their values
                choices[i].text = formset[i].cleaned_data.get('text')
                choices[i].save()
                continue

            # redirect on success
            return HttpResponseRedirect(redirect_to=reverse('polls:all-polls'))
        else:

            # return error on fail
            context['error'] = 'An error occurred'
    else:
        initial_data = {
                'user':request.user,
                'title':poll.title,
                'description':poll.description,
                'thumbnail':poll.thumbnail,
                'question':poll.question,
                'status':poll.status,
            }
        initial_formset_data = [{'text':c.text} for c in poll.choices.all()]

        # This should be in forms.py
        # extra = 3 - len(initial_formset_data)
        # EditChoiceFormset = formset_factory(ChoiceForm, extra=extra)7

        # fix choice formset to save
        poll_form = QuestionForm(initial=initial_data)
        formset = EditChoiceFormSet.EditChoiceFormset(initial=initial_formset_data)

    context['poll_form'] = poll_form
    context['formset'] = formset
    context['poll'] = poll

    # render on get request
    return render(request, 'Polls/edit_poll.html', context=context)

Polls/templates/polls/create_poll.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'polls:all-polls' %}">Home</a>
    <form action="{% url 'polls:create-poll' %}" method="POST" novalidate>
        {% csrf_token %}

        {%if error %}
            {{error}}
        {% endif %}
        {{ formset.non_form_errors }}
        <div>
            {{ poll_form.title.label }}:
            {{ poll_form.title }}
            {{ poll_form.title.errors }}
        </div>
        <div>
            {{ poll_form.description.label }}:
            {{ poll_form.description }}
            {{ poll_form.description.errors }}
        </div>
        <div>
            {{ poll_form.question.label }}:
            {{ poll_form.question }}
            {{ poll_form.question.errors }}
        </div>
        <div>
            {{ poll_form.thumbnail.label }}:
            {{ poll_form.thumbnail }}
            {{ poll_form.thumbnail.errors }}
        </div>
        <div>
            {{ poll_form.status.label }}:
            {{ poll_form.status }}
            {{ poll_form.status.errors }}
        </div>

        <!-- {{ formset.management_form }} -->

        <!-- {% for form in formset %}
        {{ form }}
        {% endfor %} -->
        <div>
            {{ formset }}
            <!-- {% if formset.errors %}
                {% for error in formset.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %} -->
        </div>
        

        <button type="submit">Create</button>
    </form>
</body>
</html>

Polls/templates/polls/detail_poll.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Polls/css/poll.css' %}">
    <title>Document</title>
</head>
<body>
    <!-- <p>{{poll.question}}</p> -->

    <form action="{% url 'polls:vote' poll.author.username poll.slug %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{poll.question}}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in poll.choices.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.text }}</label><br>
            {% endfor %}
        </fieldset>
        
        <button type="submit">Vote</button>
    </form>
</body>
</html>

Polls/templates/polls/edit_poll.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'polls:all-polls' %}">Home</a>
    <form action="{% url 'polls:edit-poll' user.username poll.slug %}" method="POST" novalidate>
        {% csrf_token %}

        {%if error %}
            {{error}}
        {% endif %}
        {{ formset.non_form_errors }}
        <div>
            {{ poll_form.title.label }}:
            {{ poll_form.title }}
            {{ poll_form.title.errors }}
        </div>
        <div>
            {{ poll_form.description.label }}:
            {{ poll_form.description }}
            {{ poll_form.description.errors }}
        </div>
        <div>
            {{ poll_form.question.label }}:
            {{ poll_form.question }}
            {{ poll_form.question.errors }}
        </div>
        <div>
            {{ poll_form.thumbnail.label }}:
            {{ poll_form.thumbnail }}
            {{ poll_form.thumbnail.errors }}
        </div>
        <div>
            {{ poll_form.status.label }}:
            {{ poll_form.status }}
            {{ poll_form.status.errors }}
        </div>

        {{ formset.management_form }}

        {% for form in formset %}
        {{ form }}
        {% endfor %}
        <div>
            <!-- {{ formset }} -->
            <!-- {% if formset.errors %}
                {% for error in formset.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %} -->
        </div>
        

        <button type="submit">Create</button>
    </form>
</body>
</html>

Polls/templates/polls/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Polls/css/poll.css' %}">
    <title>Document</title>
</head>
<body>
    {% if user.is_authenticated %}
        <a href="{% url 'polls:create-poll' %}">Create New Poll</a> | <a href="{% url 'accounts:logout' %}">Logout</a> | Current user: {{ user }}
    {% else %}
        <a href="{% url 'polls:create-poll' %}">Create New Poll</a> | <a href="{% url 'accounts:login' %}">Login</a>
    {% endif %}

    <br>
    <br>
    {% if voted_polls %}
        {% for voted_poll in voted_polls %}
            <a href="{% url 'polls:result' voted_poll.author.username voted_poll.slug %}">{{ voted_poll.title }}</a>
        {% endfor %}
    {% endif %}
    <br>
    <br>

    {% for poll in polls %}
        <a href="{% url 'polls:view-poll' poll.author.username poll.slug %}">
            <div class="card" style="width: 18rem;border:solid 1px black;">
                <img src="{% static 'Polls/img/default.jpg' %}" class="card-img-top" alt="{{ poll.title }}" style="width:100%;">
                <div class="card-body">
                    <p class="card-text">{{ poll.title }}</p>
                    <p class="card-text">{{ poll.description }}</p>
                    <small>{{ poll.status }} | by {{ poll.author.username }}| share</small> 
                    {% if user == poll.author %}
                        <p>
                            <a href="{% url 'polls:edit-poll' user.username poll.slug %}">edit</a>
                        </p>
                    {% endif %}

                    {{perms.Polls.delete_question}}
                    {% if perms.Polls.delete_question %}
                        <p>
                            <a href="{% url 'polls:edit-poll' user.username poll.slug %}">delete</a>
                        </p>
                    {% endif %}

                </div>
            </div>
        </a>
    {% endfor %}
</body>
</html>

Polls/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'polls:all-polls' %}">Home</a>
    <br>

    {{ poll.question }} <br>

    {% for choice in choices %}
        {{ choice.text }} | {{ choice.votes }} <br>
    {% endfor %}
</body>
</html>